### ISSUE TITLE
Functions linked to external webpage

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/scate-shortcourse#10]
In the rphenoscape short course tutorial, clicking on the function pk_taxon_detail() goes to this page, which doesn't have information about the function: 
https://www.rdocumentation.org/packages/rphenoscape/topics/pk_terms

Based on the behavior of these links in the main rphenoscape vignette, clicking on functions should take one to the "Reference" pages within the documentation, like this:
http://rphenoscape.phenoscape.org/reference/pk_terms.html

**Comment by hlapp** [comment]
I finally figured out what needed to be done for this to work correctly.
