### ISSUE TITLE
OntoTrace results different from first course

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/scate-shortcourse#23]
I'm running the OntoTrace query from the first short course but not getting the same results (for example, currently getting 29 species of ictalurid catfishes and 115 anatomical entities for fins and their parts; this was 29 species and 123 entities in short course document). It seems unlikely that we deleted phenotypes for catfishes. Do we have an archive of the data downloaded from the short course to see which entities aren't being returned? 

<img width="1030" alt="Screen Shot 2019-12-22 at 3 27 30 PM" src="https://user-images.githubusercontent.com/957012/71328777-76e97e80-24d1-11ea-935c-d6ce27a3148b.png">

**Comment by wdahdul** [comment]
The next step in the vignette also shows different results. When looking at this query in facetted browsing: 
- Anatomical entity = ‘pelvic fin’
- Quality = ‘present’
- Taxon = ‘Ictalurus australis’

Clicking on 'inferred presence' shows 2 phenotypes (supporting states) currently, but 3 were reported in the June course materials. The June results included ‘pelvic splint size’, but I just checked the Phenex file (Lundberg 1992), and this state isn’t assigned to Ictalurus australis, so not sure how that supporting state was inferred in the first place?

**Comment by balhoff** [comment]
There were some changes to presence-absence inference in the meantime. This may be the cause of what you're seeing. I don't have the previous results though.

**Comment by wdahdul** [comment]
thanks Jim
