### ISSUE TITLE
Warnings from PARAMO vignette

### ISSUE THREAD

**Issue by hlapp** [phenoscape/scate-shortcourse#28]
I get the following warnings from the PARAMO vignette when rendering it for the course website:

```R
Warning messages:
1: In FUN(X[[i]], ...) :
  cannot unserialize ALTVEC object of class 'wrap_logical' from package 'base'; returning length zero vector
2: In FUN(X[[i]], ...) :
  cannot unserialize ALTVEC object of class 'wrap_logical' from package 'base'; returning length zero vector
```
I can't tell how consequential these are, and what I can do to make them go away. If they result in bad output, someone who does not see these warnings needs to render the vignette so it appears properly on the website.

**Comment by uyedaj** [comment]
Seems to be related to [this problem](https://r.789695.n4.nabble.com/wrap-logical-warning-message-when-loading-objects-created-in-R-3-6-in-an-R-3-5-session-td4758937.html), will try to figure out but perhaps you can help me by letting me know your sessionInfo and how to reproduce it?

**Comment by hlapp** [comment]
Yes, that sounds like it could be it. I was (am) indeed running R 3.5.x (and this is also the minimum required version in `DESCRIPTION`). (Specifically, I am running R version 3.5.2 (2018-12-20).) Were you indeed saving the data files from R 3.6.x?

I can post the full session info, but if you're looking for specific packages, I can maybe make it easier by fishing out those versions?

**Comment by hlapp** [comment]
For the record, this wasn't a problem with the PARAMO vignette itself, but with two of the data files it uses.
